# Generated by Django 5.1.1 on 2025-01-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='creatred_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='creatred_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creatred_at',
            new_name='created_at',
        ),
    ]
